spring:
  datasource:
    url: "${db.url:jdbc:postgresql://localhost:5432/postgres}"
    username: "${db.username:user}"
    password: "${db.password:pass}"
#    driver-class-name: org.postgresql.Driver


springdoc:
  swagger-ui:
    path: "/swagger/"
  api-docs:
    path: "/swagger/swagger.json"